### PR TITLE
fixes #68: overriding express options.

### LINKED ISSUE #68: overriding express options
It seems that swaggerize express is overriding some of my options that I set for my express app. I have set `json spaces` to 2, but it gets overridden [here](https://github.com/krakenjs/swaggerize-express/blob/master/lib/index.js#L52-L65).

Here is my example code:

```js
'use strict';

var http = require('http');
var express = require('express');
var swaggerize = require('swaggerize-express');
var app = express();
var server = http.createServer(app);

app.disable('x-powered-by');
app.set('json spaces', 2);

var compression = require('compression');
var bodyParser = require('body-parser');

app.use(compression());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.use(swaggerize({
  api: require('./resources'),
  docspath: '/api-docs',
  handlers: './routes'
});

server.listen(process.env.PORT || 8000)
  .on('listening', console.log.bind(null, 'Server started'))
  .on('error', console.log.bind(null));
```

Expected Behavior:

Api endpoints should have the correctly set `json spaces` option (for pretty printed json)

Actual Behavior:

Api endpoints are not pretty printed because the setting is getting overridden.

Proposed Solution:

I know that `json spaces` isn't the only option that is being overriden, but I agree that the ones being overridden are sensible defaults for a majority of people. My only problem with it is that it is unexpected behavior based on my settings. I don't think that you can detect whether or not a setting was set on the user's end, but perhaps just leaving it up to the user to choose the settings would be best.

### PR DESCRIPTION
**Pull request by jsdevel**
* Removing the express option overrides as middleware should not configure express apps.

### CODE REVIEW

**Comment by tlivings** [comment]
Based on what? For one thing this is not middleware, it is simply using the `mount` event to provide configuration.

**Comment by jsdevel** [comment]
> For one thing this is not middleware...

If it isn't middleware, then it shouldn't be wired into express applications using `app.use`.

http://expressjs.com/4x/api.html#app.use
https://github.com/krakenjs/swaggerize-express#manual-usage

**Comment by tlivings** [comment]
It adds middleware through this factory. By virtue of using `app.use(swaggerize(options))` the application is configured, middleware is injected, but `swaggerize` function itself is not middleware. This is a similar pattern to many `kraken` components.

Anyway, these statements are based on what? An error or known issue? An opinion? Something confusing? Would it help if the way it configures `express` by default be helpful?

**Comment by jsdevel** [comment]
> Based on what?

* #79 was an anti-pattern. Express should be configured via the `app.set` API for clarity.
* From the [express docs](http://expressjs.com/guide/using-middleware.html) `Middleware is a function with access to the request object (req), the response object (res), and the next middleware in the application’s request-response cycle, commonly denoted by a variable named next.`

**Comment by jsdevel** [comment]
> It adds middleware through this factory.

Why not have this as your API then?

```
swaggerize({
  app: app
  ...
});
```

`swaggerize` is overly opinionated for no good reason.  Can you justify why these options were added in the first place?

```
*           'x-powered-by': false,
*           'trust proxy': false,
*           'jsonp callback name': null,
*           'json replacer': null,
*           'json spaces': 0,
*           'case sensitive routing': false,
*           'strict routing': false,
*           'views': null,
*           'view cache': false,
*           'view engine': false
```

**Comment by jsdevel** [comment]
Additionally...

> For one thing this is not middleware...

Then why is it referred to as such in the README?  For one thing this is not middleware

```
After using this middleware...
```

**Comment by tlivings** [comment]
`swaggerize-express` is used for building APIs. The default options were chosen considering this over building an application (for example, disabled views). I can revisit the decisions on some of these options, since certainly I'd actually rather enable strict routing and case sensitive since we drive off the spec. Are there specific options you didn't think were right, or just any option in general?

As I said, if the documentation is confusing, I'm happy to update it for clarity.

Regarding being "too opinionated", this tool is definitely opinionated. It has opinions about how you should define APIs, how it will bind them, etc. It's a tool for a specific job, and if you'd like less opinions you can definitely provide similar functionality by simply using `swaggerize-routes`.

I realize the use of `app.use` doesn't make you happy, but the fact is this isn't a very unusual pattern, and the neat little trick with `mount` provides a very elegant mechanism for configuration over injecting the app. It also allows you to mix several such modules together using the same pattern.

**Comment by jsdevel** [comment]
> Are there specific options you didn't think were right, or just any option in general?

The only option that makes sense in the context of `swaggerize-express` is `mountpath` as it relates to how `swaggerize` is added to express.  Everything else though isn't called out anywhere in the swagger spec (I.E. strict routing) from what I can tell and therefore should be left to the originating app.

Regarding `mountpath`, even that I feel could be left up to the originating app and defined in the getting starting sections of the README.

> Regarding being "too opinionated", this tool is definitely opinionated.

Considering the title of the repo:
```
Design-driven apis with swagger 2.0 and express.
```

I would expect that the opinions of the framework deal with how I structure `swagger` _within_ my app, not how the framework is going to _configure_ my app.

> I realize the use of app.use doesn't make you happy...

I'm completely fine with `app.use`; however, it is both counterintuitive and against the contract that `app.use` provides.  Can you imagine what would happen if I wanted to use 5 different pieces of middleware and they each had different opinions on what my `json` replacer should do?  It would be a mess, let alone a waste of startup processing.

**Comment by jasisk** [comment]
> * From the [express docs](http://expressjs.com/guide/using-middleware.html) `Middleware is a function with access to the request object (req), the response object (res), and the next middleware in the application’s request-response cycle, commonly denoted by a variable named next.`

Correct but that's not what is happening here.

When you call `swaggerize(opts)`, no middleware is returned (in the true interpretation of "middleware"). [An ephemeral app instance is created which waits to be mounted](https://github.com/krakenjs/swaggerize-express/blob/dfc8ccce13a0a6196a46b7f6c6e001176e647523/lib/index.js#L32). [Upon being mounted](https://github.com/krakenjs/swaggerize-express/blob/dfc8ccce13a0a6196a46b7f6c6e001176e647523/lib/index.js#L34), we [gain access to the parent app instance](https://github.com/krakenjs/swaggerize-express/blob/dfc8ccce13a0a6196a46b7f6c6e001176e647523/lib/index.js#L46), etc. We [pop the ephemeral app instance off the stack](https://github.com/krakenjs/swaggerize-express/blob/dfc8ccce13a0a6196a46b7f6c6e001176e647523/lib/index.js#L49) and [start orchestrating the parent app](https://github.com/krakenjs/swaggerize-express/blob/dfc8ccce13a0a6196a46b7f6c6e001176e647523/lib/index.js#L66-L82).

In other words, the parent app is intentionally mutated. If your app is exclusively leveraging swaggerize, these options (admittedly some of which are opinion) will accomplish what is necessary. If not, you're better off creating a clean app instance, `app.use(swaggerize())` on it, and mount it onto your parent app. This sort of isolation is a good practice for a number of reasons (independent error handling, can be trivially pulled out into it's own process, flattens the route map, etc).

``` js
var express = require('express');
var security = require('./lib/security'); // ... just an example ...
var app = express();
var api = express();

api.use(security()); // maybe auth logic or rate limiting or something
api.use(swaggerize());

app.use('/api', api);

app.listen(0);
```

That said, using the ephemeral app pattern vs `swaggerize(app)` is certainly an opinionated design-choice. the former does _does_ afford us a tiny amount of lifecycle information we would lose with the latter. If you want to manage that yourself, you can avoid that bootstapping with something like:

``` js
var routes = require('swaggerize-express/lib/expressroutes');
var express = require('express');
var app = express();

var router = new express.Router();
routes(router, options);

app.use('/api', router);

app.listen(0);
```

**Comment by jsdevel** [comment]
> Correct but that's not what is happening here.

I understand what is happening here.  The point of this discussion is that the design can be more intuitive / less encroaching.  With #79, you're basically saying `don't use app.set`.  Otherwise you'd have this:

```
// configuration not covered by swaggerize
app.set('something',...);
... more configuration not covered by swaggerize

app.use(swaggerize({
  express: {
    'something different': 'bla'
  }
});
```

Imagine using this framework now with other frameworks that require the same treatment for encroaching configuration altering:

```
app.use(swaggerize({
  express: {
    'views': 'bla'
  }
});

app.use(someOtherFramework({
  express: {
    'views': 'bla'
  }
});
```

**Comment by jsdevel** [comment]
Regarding `mountpath`, it would be just as easy to add `apiBasePath` within `swaggerize` without altering the `parent` app on https://github.com/krakenjs/swaggerize-express/blob/master/lib/index.js#L34 I.E.:

```
  app.mountpath = options.api.apiBasePath;
```

**Comment by tlivings** [comment]
So the complaint is that `swaggerize-express` potentially overwrites express options you have explicitly set? If that's the root of the issue, then I can look at checking before blowing away where applicable.

**Comment by jsdevel** [comment]
> So the complaint is that swaggerize-express potentially overwrites express options you have explicitly set?

Correct.  On the project I'm working on there is a need to serve both the api via swagger, _and_ HTML.  After trying to get `view engine` to work for half an hour or so to no avail, I then discovered that it was being set by `swaggerize-express` for no apparent reason.

> If that's the root of the issue, then I can look at checking before blowing away where applicable.

Ultimately I have little say in the implementation `as I'm not a maintainer` :smirk:.  If it were my project I would remove anything that's not of my concern I.E. `x-powered-by` or `views`.

Opinions are like the wind, but it's where any why they exist.  To me, `views` and `x-powered-by` would be appropriate opinions for a framework like `kraken` or `meteor`.  `swaggerize-express` is all about swagger if I'm not mistaken.

**Comment by jsdevel** [comment]
Just removed `mountpath` as well.  What would happen if multiple frameworks altered `mountpath` on the parent?

**Comment by jsdevel** [comment]
@tlivings sorry for the back and forth over this.  Can this be merged?  Note that the mount path can be overridded with `app.use('/my/mount/path', swaggerize({...})0;`.

**Comment by tlivings** [comment]
I'm not sure what the purpose of this change is at this point. Just to avoid overriding already set express options? If that's the case then we can address it in a different change.

**Comment by jsdevel** [comment]
> I'm not sure what the purpose of this change is at this point...

The purpose is to avoid doing anything that isn't necessary.

**Comment by tlivings** [comment]
Still unclear what `non-express way` means. Please re-read https://github.com/krakenjs/swaggerize-express/pull/80#issuecomment-149344047. 

That being said, we can continue to pursue not overwriting the express options (the title of the PR), but I don't see a reason to change the behavior of how it mounts and defines routes.

**Comment by jsdevel** [comment]
> If not, you're better off creating a clean app instance, app.use(swaggerize()) on it, and mount it onto your parent app. 

Isn't that the only way to use `swaggerize-express`?  #80 (comment) proves my point.

I still don't feel you've answered my question though from https://github.com/krakenjs/swaggerize-express/pull/80#issuecomment-149354278.  Specifically this

> What would happen if multiple frameworks altered mountpath on the parent?

**Comment by tlivings** [comment]
The intent of the `swaggerize-express` module is to bind express handlers to an API document's routes definition.

It is not intended to be used in conjunction with multiple APIs or applications, but if doing so - the best practice is to use sub apps (i.e treat each of these as a sub app), and then add them to a parent.

**Comment by jsdevel** [comment]
> It is not intended to be used in conjunction with multiple APIs or applications,...

My project has a need to use it with multiple applications.  Sub apps isn't an option for us.

**Comment by grawk** [comment]
Long-time listener, first-time caller: would it be conceivable to make the mount function a configurable option?

**Comment by tlivings** [comment]
Why isn't a sub app an option?

**Comment by jsdevel** [comment]
> Why isn't a sub app an option?

I can't get into too many details (private / proprietary project), but basically a legacy project that we can't do too much refactoring in.  We were hoping to be able to add `swaggerize-express` without too much hassle, but our hopes are being damaged a bit with the pervasiveness of these defaults.

Tell me, why is it necessary to modify mountpath?  We're using my branch and following the instructions in the README without any problems at all.

**Comment by jsdevel** [comment]
> Why isn't a sub app an option?

Also, if used as a sub-app, I believe `swagger` would no longer be available to our parent app where we need it.

**Comment by tlivings** [comment]
This doesn't work?

```javascript
var subapp = express();

subapp.use(swaggerize(options));

app.use(path, subapp);
```

?

**Comment by jsdevel** [comment]
`app` will not have access to `swagger`.  Only `subapp` will no?

**Comment by tlivings** [comment]
Have access how?

**Comment by jsdevel** [comment]
From the [README](https://github.com/krakenjs/swaggerize-express#manual-usage):

> After using this middleware, a new property will be available on the app called swagger

**Comment by jsdevel** [comment]
@tlivings I feel like there's been a lot of deliberating on this PR (coming up on a month and a half since it was opened).

Ideally I'd like to see these changes merged into `swaggerize-express`, but I have no problem forking and publishing something else.  I'd like to add support for file relative definition references, but wouldn't want to if this PR doesn't make it.

Looking forward to your response

--jsdevel

**Comment by tlivings** [comment]
You mention that you need access to `app.swagger` from the parent app. Why? Can't this simply be exposed manually to the parent app through a `mount` event on the child swagger app?

In regards to your last comment: there is a lot of deliberating because you are changing semantics based on your own requirements regardless of the fact that there are other ways to achieve this.

I'd like to support your requirement for not overriding pre-set `express` options, but I don't think this PR properly fulfills that. In addition, if using `swaggerize-express` in a sub-app, there is no need to worry about the express options, since it should not affect the parent.

If you really do want to take this in another direction, that's fine too. The intent of `swaggerize-routes` is to provide just that - the capability to build additional integrations (as seen in `swaggerize-restify`).

**Comment by jsdevel** [comment]
> I'd like to support your requirement for not overriding pre-set express options...

How does this PR not properly fulfill that?

**Pull request closed without merging**
